# -*- coding: utf-8 -*-

# 只需要在这个列表中添加以下 available_cities 中的城市, 如果只需要扒取一个城市也需要使用一个括号包围, 如 (u'广州',)
cities = (u'北京', u'广州',)

# 以下注释的字母表示的是省份名字的拼音首字母
available_cities = (
    # A
    u'合肥',
    u'芜湖',
    u'蚌埠',
    u'阜阳',
    u'淮南',
    u'安庆',
    u'宿州',
    u'六安',
    u'淮北',
    u'滁州',
    u'马鞍山',
    u'铜陵',
    u'宣城',
    u'亳州',
    u'黄山',
    u'池州',
    u'巢湖',
    u'和县',
    u'霍邱',
    u'桐城',
    u'宁国',
    u'天长',
    u'东至',
    u'无为',

    # B
    u'北京',

    # F
    u'福州',
    u'厦门',
    u'泉州',
    u'莆田',
    u'漳州',
    u'宁德',
    u'三明',
    u'南平',
    u'龙岩',
    u'武夷山',
    u'石狮',
    u'晋江',
    u'南安',
    u'龙海',
    u'上杭',
    u'福安',
    u'福鼎',
    u'安溪',
    u'永春',
    u'永安',
    u'漳浦',

    # G
    u'深圳',
    u'广州',
    u'东莞',
    u'佛山',
    u'中山',
    u'珠海',
    u'惠州',
    u'江门',
    u'汕头',
    u'湛江',
    u'肇庆',
    u'茂名',
    u'揭阳',
    u'梅州',
    u'清远',
    u'阳江',
    u'韶关',
    u'河源',
    u'云浮',
    u'汕尾',
    u'潮州',
    u'台山',
    u'阳春',
    u'顺德',
    u'惠东',
    u'博罗',
    u'海丰',
    u'开平',
    u'陆丰',

    u'南宁',
    u'柳州',
    u'桂林',
    u'玉林',
    u'梧州',
    u'北海',
    u'贵港',
    u'钦州',
    u'百色',
    u'河池',
    u'来宾',
    u'贺州',
    u'防城港',
    u'崇左',
    u'桂平',
    u'北流',
    u'博白',
    u'岑溪',

    u'贵阳',
    u'遵义',
    u'黔东南',
    u'黔南',
    u'六盘水',
    u'毕节',
    u'铜仁',
    u'安顺',
    u'黔西南',
    u'仁怀',
    u'清镇',

    u'兰州',
    u'天水',
    u'白银',
    u'庆阳',
    u'平凉',
    u'酒泉',
    u'张掖',
    u'武威',
    u'定西',
    u'金昌',
    u'陇南',
    u'临夏',
    u'嘉峪关',
    u'甘南',
    u'敦煌',

    # H

    u'海口',
    u'三亚',
    u'五指山',
    u'三沙',
    u'琼海',
    u'文昌',
    u'万宁',
    u'屯昌',
    u'琼中',
    u'陵水',
    u'东方',
    u'定安',
    u'澄迈',
    u'保亭',
    u'白沙',
    u'儋州',

    u'郑州',
    u'洛阳',
    u'新乡',
    u'南阳',
    u'许昌',
    u'平顶山',
    u'安阳',
    u'焦作',
    u'商丘',
    u'开封',
    u'濮阳',
    u'周口',
    u'信阳',
    u'驻马店',
    u'漯河',
    u'三门峡',
    u'鹤壁',
    u'济源',
    u'明港',
    u'鄢陵',
    u'禹州',
    u'长葛',
    u'灵宝',
    u'杞县',
    u'汝州',
    u'项城',
    u'偃师',
    u'长垣',
    u'滑县',
    u'林州',
    u'沁阳',
    u'孟州',
    u'温县',
    u'尉氏',
    u'兰考',
    u'通许',
    u'新安',
    u'伊川',
    u'孟津',
    u'宜阳',
    u'舞钢',
    u'永城',
    u'睢县',
    u'鹿邑',
    u'渑池',
    u'沈丘',
    u'太康',
    u'商水',
    u'淇县',
    u'浚县',
    u'范县',
    u'固始',
    u'淮滨',
    u'邓州',
    u'新野',

    u'哈尔滨',
    u'大庆',
    u'齐齐哈尔',
    u'牡丹江',
    u'绥化',
    u'佳木斯',
    u'鸡西',
    u'双鸭山',
    u'鹤岗',
    u'黑河',
    u'伊春',
    u'七台河',
    u'大兴安岭',
    u'安达',
    u'肇东',
    u'肇州',

    u'武汉',
    u'宜昌',
    u'襄阳',
    u'荆州',
    u'十堰',
    u'黄石',
    u'孝感',
    u'黄冈',
    u'恩施',
    u'荆门',
    u'咸宁',
    u'鄂州',
    u'随州',
    u'潜江',
    u'天门',
    u'仙桃',
    u'神农架',
    u'宜都',
    u'汉川',
    u'枣阳',
    u'武穴',
    u'钟祥',
    u'京山',
    u'沙洋',
    u'松滋',
    u'广水',
    u'赤壁',
    u'老河口',
    u'谷城',
    u'宜城',
    u'南漳',
    u'云梦',
    u'安陆',
    u'大悟',
    u'孝昌',
    u'当阳',
    u'枝江',
    u'嘉鱼',
    u'随县',

    u'长沙',
    u'株洲',
    u'益阳',
    u'常德',
    u'衡阳',
    u'湘潭',
    u'岳阳',
    u'郴州',
    u'邵阳',
    u'怀化',
    u'永州',
    u'娄底',
    u'湘西',
    u'张家界',
    u'醴陵',
    u'澧县',
    u'桂阳',
    u'资兴',
    u'永兴',
    u'常宁',
    u'祁东',
    u'衡东',
    u'冷水江',
    u'涟源',
    u'双峰',
    u'邵阳县',
    u'邵东',
    u'沅江',
    u'南县',
    u'祁阳',
    u'湘阴',
    u'华容',
    u'慈利',
    u'攸县',

    u'石家庄',
    u'保定',
    u'唐山',
    u'廊坊',
    u'邯郸',
    u'秦皇岛',
    u'沧州',
    u'邢台',
    u'衡水',
    u'张家口',
    u'承德',
    u'定州',
    u'馆陶',
    u'张北',
    u'赵县',
    u'正定',
    u'迁安市',
    u'任丘',
    u'三河',
    u'武安',
    u'雄安新区',
    u'燕郊',
    u'涿州',
    u'河间',
    u'黄骅',
    u'沧县',
    u'磁县',
    u'涉县',
    u'霸州',
    u'香河',
    u'固安',
    u'遵化市',
    u'迁西',
    u'玉田',
    u'滦南',
    u'沙河',
    # J

    u'苏州',
    u'南京',
    u'无锡',
    u'常州',
    u'徐州',
    u'南通',
    u'扬州',
    u'盐城',
    u'淮安',
    u'连云港',
    u'泰州',
    u'宿迁',
    u'镇江',
    u'沭阳',
    u'大丰',
    u'如皋',
    u'启东',
    u'溧阳',
    u'海门',
    u'东海',
    u'扬中',
    u'兴化',
    u'新沂',
    u'泰兴',
    u'如东',
    u'邳州',
    u'沛县',
    u'靖江',
    u'建湖',
    u'海安',
    u'东台',
    u'丹阳',
    u'宝应县',
    u'灌南',
    u'灌云',
    u'姜堰',
    u'金坛',
    u'昆山',
    u'泗洪',
    u'泗阳',
    u'句容',
    u'射阳',
    u'阜宁',
    u'响水',
    u'盱眙',
    u'金湖',

    u'南昌',
    u'赣州',
    u'九江',
    u'宜春',
    u'吉安',
    u'上饶',
    u'萍乡',
    u'抚州',
    u'景德镇',
    u'新余',
    u'鹰潭',
    u'永新',
    u'乐平',
    u'进贤',
    u'分宜',
    u'丰城',
    u'樟树',
    u'高安',
    u'余江',
    u'南城',
    u'浮梁',

    u'长春',
    u'吉林',
    u'四平',
    u'延边',
    u'松原',
    u'白城',
    u'通化',
    u'白山',
    u'辽源',
    u'公主岭',
    u'梅河口',
    u'扶余',
    u'长岭',
    u'桦甸',
    u'磐石',
    u'梨树县',
    # L

    u'沈阳',
    u'大连',
    u'鞍山',
    u'锦州',
    u'抚顺',
    u'营口',
    u'盘锦',
    u'朝阳',
    u'丹东',
    u'辽阳',
    u'本溪',
    u'葫芦岛',
    u'铁岭',
    u'阜新',
    u'庄河',
    u'瓦房店',
    u'灯塔',
    u'凤城',
    u'北票',
    u'开原',
    # N

    u'银川',
    u'吴忠',
    u'石嘴山',
    u'中卫',
    u'固原',

    u'呼和浩特',
    u'包头',
    u'赤峰',
    u'鄂尔多斯',
    u'通辽',
    u'呼伦贝尔',
    u'巴彦淖尔市',
    u'乌兰察布',
    u'锡林郭勒',
    u'兴安盟',
    u'乌海',
    u'阿拉善盟',
    u'海拉尔',
    # Q

    u'西宁',
    u'海西',
    u'海北',
    u'果洛',
    u'海东',
    u'黄南',
    u'玉树',
    u'海南',
    u'格尔木',
    # S

    u'青岛',
    u'济南',
    u'烟台',
    u'潍坊',
    u'临沂',
    u'淄博',
    u'济宁',
    u'泰安',
    u'聊城',
    u'威海',
    u'枣庄',
    u'德州',
    u'日照',
    u'东营',
    u'菏泽',
    u'滨州',
    u'莱芜',
    u'章丘',
    u'垦利',
    u'诸城',
    u'寿光',
    u'龙口',
    u'曹县',
    u'单县',
    u'肥城',
    u'高密',
    u'广饶',
    u'桓台',
    u'莒县',
    u'莱州',
    u'蓬莱',
    u'青州',
    u'荣成',
    u'乳山',
    u'滕州',
    u'新泰',
    u'招远',
    u'邹城',
    u'邹平',
    u'临清',
    u'茌平',
    u'郓城',
    u'博兴',
    u'东明',
    u'巨野',
    u'无棣',
    u'齐河',
    u'微山',
    u'禹城',
    u'临邑',
    u'乐陵',
    u'莱阳',
    u'宁津',
    u'高唐',
    u'莘县',
    u'阳谷',
    u'冠县',
    u'平邑',
    u'郯城',
    u'沂源',
    u'汶上',
    u'梁山',
    u'利津',
    u'沂南',
    u'栖霞',
    u'宁阳',
    u'东平',
    u'昌邑',
    u'安丘',
    u'昌乐',
    u'临朐',
    u'鄄城',

    u'太原',
    u'临汾',
    u'大同',
    u'运城',
    u'晋中',
    u'长治',
    u'晋城',
    u'阳泉',
    u'吕梁',
    u'忻州',
    u'朔州',
    u'临猗',
    u'清徐',
    u'柳林',
    u'高平',
    u'泽州',
    u'襄垣',
    u'孝义',

    u'西安',
    u'咸阳',
    u'宝鸡',
    u'渭南',
    u'汉中',
    u'榆林',
    u'延安',
    u'安康',
    u'商洛',
    u'铜川',
    u'神木',
    u'韩城',
    u'府谷',
    u'靖边',
    u'定边',

    u'成都',
    u'绵阳',
    u'德阳',
    u'南充',
    u'宜宾',
    u'自贡',
    u'乐山',
    u'泸州',
    u'达州',
    u'内江',
    u'遂宁',
    u'攀枝花',
    u'眉山',
    u'广安',
    u'资阳',
    u'凉山',
    u'广元',
    u'雅安',
    u'巴中',
    u'阿坝',
    u'甘孜',
    u'安岳',
    u'广汉',
    u'简阳',
    u'仁寿',
    u'射洪',
    u'大竹',
    u'宣汉',
    u'渠县',
    u'长宁',
    # X

    u'乌鲁木齐',
    u'昌吉',
    u'巴音郭楞',
    u'伊犁',
    u'阿克苏',
    u'喀什',
    u'哈密',
    u'克拉玛依',
    u'博尔塔拉',
    u'吐鲁番',
    u'和田',
    u'石河子',
    u'克孜勒苏',
    u'阿拉尔',
    u'五家渠',
    u'图木舒克',
    u'库尔勒',
    u'阿勒泰',
    u'塔城',

    u'拉萨',
    u'日喀则',
    u'山南',
    u'林芝',
    u'昌都',
    u'那曲',
    u'阿里',
    u'日土',
    u'改则',
    # Y

    u'昆明',
    u'曲靖',
    u'大理',
    u'红河',
    u'玉溪',
    u'丽江',
    u'文山',
    u'楚雄',
    u'西双版纳',
    u'昭通',
    u'德宏',
    u'普洱',
    u'保山',
    u'临沧',
    u'迪庆',
    u'怒江',
    u'弥勒',
    u'安宁',
    u'宣威',
    # Z

    u'杭州',
    u'宁波',
    u'温州',
    u'金华',
    u'嘉兴',
    u'台州',
    u'绍兴',
    u'湖州',
    u'丽水',
    u'衢州',
    u'舟山',
    u'乐清',
    u'瑞安',
    u'义乌',
    u'余姚',
    u'诸暨',
    u'象山',
    u'温岭',
    u'桐乡',
    u'慈溪',
    u'长兴',
    u'嘉善',
    u'海宁',
    u'德清',
    u'东阳',
    u'安吉',
    u'苍南',
    u'临海',
    u'永康',
    u'玉环',
    u'平湖',
    u'海盐',
    u'武义县',
    u'嵊州',
    u'新昌',
    u'江山',
    u'平阳',

    # 其他
    u'香港',
    u'澳门',
    u'台湾',
    u'全国',
    u'其他',

    # 海外
    u'洛杉矶',
    u'旧金山',
    u'纽约',
    u'多伦多',
    u'温哥华',
    u'伦敦',
    u'莫斯科',
    u'首尔',
    u'东京',
    u'新加坡',
    u'曼谷',
    u'清迈',
    u'迪拜',
    u'奥克兰',
    u'悉尼',
    u'墨尔本',
    u'其他海外城市',

)

available_cities_map = {
    # A
    u'合肥': 'http://hf.58.com/chuzu/',
    u'芜湖': 'http://wuhu.58.com/chuzu/',
    u'蚌埠': 'http://bengbu.58.com/chuzu/',
    u'阜阳': 'http://fy.58.com/chuzu/',
    u'淮南': 'http://hn.58.com/chuzu/',
    u'安庆': 'http://anqing.58.com/chuzu/',
    u'宿州': 'http://suzhou.58.com/chuzu/',
    u'六安': 'http://la.58.com/chuzu/',
    u'淮北': 'http://huaibei.58.com/chuzu/',
    u'滁州': 'http://chuzhou.58.com/chuzu/',
    u'马鞍山': 'http://mas.58.com/chuzu/',
    u'铜陵': 'http://tongling.58.com/chuzu/',
    u'宣城': 'http://xuancheng.58.com/chuzu/',
    u'亳州': 'http://bozhou.58.com/chuzu/',
    u'黄山': 'http://huangshan.58.com/chuzu/',
    u'池州': 'http://chizhou.58.com/chuzu/',
    u'巢湖': 'http://ch.58.com/chuzu/',
    u'和县': 'http://hexian.58.com/chuzu/',
    u'霍邱': 'http://hq.58.com/chuzu/',
    u'桐城': 'http://tongcheng.58.com/chuzu/',
    u'宁国': 'http://ningguo.58.com/chuzu/',
    u'天长': 'http://tianchang.58.com/chuzu/',
    u'东至': 'http://dongzhi.58.com/chuzu/',
    u'无为': 'http://wuweixian.58.com/chuzu/',

    # B
    u'北京': 'http://bj.58.com/chuzu/',

    # F
    u'福州': 'http://fz.58.com/chuzu/',
    u'厦门': 'http://xm.58.com/chuzu/',
    u'泉州': 'http://qz.58.com/chuzu/',
    u'莆田': 'http://pt.58.com/chuzu/',
    u'漳州': 'http://zhangzhou.58.com/chuzu/',
    u'宁德': 'http://nd.58.com/chuzu/',
    u'三明': 'http://sm.58.com/chuzu/',
    u'南平': 'http://np.58.com/chuzu/',
    u'龙岩': 'http://ly.58.com/chuzu/',
    u'武夷山': 'http://wuyishan.58.com/chuzu/',
    u'石狮': 'http://shishi.58.com/chuzu/',
    u'晋江': 'http://jinjiangshi.58.com/chuzu/',
    u'南安': 'http://nananshi.58.com/chuzu/',
    u'龙海': 'http://longhai.58.com/chuzu/',
    u'上杭': 'http://shanghangxian.58.com/chuzu/',
    u'福安': 'http://fuanshi.58.com/chuzu/',
    u'福鼎': 'http://fudingshi.58.com/chuzu/',
    u'安溪': 'http://anxixian.58.com/chuzu/',
    u'永春': 'http://yongchunxian.58.com/chuzu/',
    u'永安': 'http://yongan.58.com/chuzu/',
    u'漳浦': 'http://zhangpu.58.com/chuzu/',

    # G
    u'深圳': 'http://sz.58.com/chuzu/',
    u'广州': 'http://gz.58.com/chuzu/',
    u'东莞': 'http://dg.58.com/chuzu/',
    u'佛山': 'http://fs.58.com/chuzu/',
    u'中山': 'http://zs.58.com/chuzu/',
    u'珠海': 'http://zh.58.com/chuzu/',
    u'惠州': 'http://huizhou.58.com/chuzu/',
    u'江门': 'http://jm.58.com/chuzu/',
    u'汕头': 'http://st.58.com/chuzu/',
    u'湛江': 'http://zhanjiang.58.com/chuzu/',
    u'肇庆': 'http://zq.58.com/chuzu/',
    u'茂名': 'http://mm.58.com/chuzu/',
    u'揭阳': 'http://jy.58.com/chuzu/',
    u'梅州': 'http://mz.58.com/chuzu/',
    u'清远': 'http://qingyuan.58.com/chuzu/',
    u'阳江': 'http://yj.58.com/chuzu/',
    u'韶关': 'http://sg.58.com/chuzu/',
    u'河源': 'http://heyuan.58.com/chuzu/',
    u'云浮': 'http://yf.58.com/chuzu/',
    u'汕尾': 'http://sw.58.com/chuzu/',
    u'潮州': 'http://chaozhou.58.com/chuzu/',
    u'台山': 'http://taishan.58.com/chuzu/',
    u'阳春': 'http://yangchun.58.com/chuzu/',
    u'顺德': 'http://sd.58.com/chuzu/',
    u'惠东': 'http://huidong.58.com/chuzu/',
    u'博罗': 'http://boluo.58.com/chuzu/',
    u'海丰': 'http://haifengxian.58.com/chuzu/',
    u'开平': 'http://kaipingshi.58.com/chuzu/',
    u'陆丰': 'http://lufengshi.58.com/chuzu/',

    u'南宁': 'http://nn.58.com/chuzu/',
    u'柳州': 'http://liuzhou.58.com/chuzu/',
    u'桂林': 'http://gl.58.com/chuzu/',
    u'玉林': 'http://yulin.58.com/chuzu/',
    u'梧州': 'http://wuzhou.58.com/chuzu/',
    u'北海': 'http://bh.58.com/chuzu/',
    u'贵港': 'http://gg.58.com/chuzu/',
    u'钦州': 'http://qinzhou.58.com/chuzu/',
    u'百色': 'http://baise.58.com/chuzu/',
    u'河池': 'http://hc.58.com/chuzu/',
    u'来宾': 'http://lb.58.com/chuzu/',
    u'贺州': 'http://hezhou.58.com/chuzu/',
    u'防城港': 'http://fcg.58.com/chuzu/',
    u'崇左': 'http://chongzuo.58.com/chuzu/',
    u'桂平': 'http://guipingqu.58.com/chuzu/',
    u'北流': 'http://beiliushi.58.com/chuzu/',
    u'博白': 'http://bobaixian.58.com/chuzu/',
    u'岑溪': 'http://cenxi.58.com/chuzu/',

    u'贵阳': 'http://gy.58.com/chuzu/',
    u'遵义': 'http://zunyi.58.com/chuzu/',
    u'黔东南': 'http://qdn.58.com/chuzu/',
    u'黔南': 'http://qn.58.com/chuzu/',
    u'六盘水': 'http://lps.58.com/chuzu/',
    u'毕节': 'http://bijie.58.com/chuzu/',
    u'铜仁': 'http://tr.58.com/chuzu/',
    u'安顺': 'http://anshun.58.com/chuzu/',
    u'黔西南': 'http://qxn.58.com/chuzu/',
    u'仁怀': 'http://renhuaishi.58.com/chuzu/',
    u'清镇': 'http://qingzhen.58.com/chuzu/',

    u'兰州': 'http://lz.58.com/chuzu/',
    u'天水': 'http://tianshui.58.com/chuzu/',
    u'白银': 'http://by.58.com/chuzu/',
    u'庆阳': 'http://qingyang.58.com/chuzu/',
    u'平凉': 'http://pl.58.com/chuzu/',
    u'酒泉': 'http://jq.58.com/chuzu/',
    u'张掖': 'http://zhangye.58.com/chuzu/',
    u'武威': 'http://wuwei.58.com/chuzu/',
    u'定西': 'http://dx.58.com/chuzu/',
    u'金昌': 'http://jinchang.58.com/chuzu/',
    u'陇南': 'http://ln.58.com/chuzu/',
    u'临夏': 'http://linxia.58.com/chuzu/',
    u'嘉峪关': 'http://jyg.58.com/chuzu/',
    u'甘南': 'http://gn.58.com/chuzu/',
    u'敦煌': 'http://dunhuang.58.com/chuzu/',

    # H

    u'海口': 'http://haikou.58.com/chuzu/',
    u'三亚': 'http://sanya.58.com/chuzu/',
    u'五指山': 'http://wzs.58.com/chuzu/',
    u'三沙': 'http://sansha.58.com/chuzu/',
    u'琼海': 'http://qh.58.com/chuzu/',
    u'文昌': 'http://wenchang.58.com/chuzu/',
    u'万宁': 'http://wanning.58.com/chuzu/',
    u'屯昌': 'http://tunchang.58.com/chuzu/',
    u'琼中': 'http://qiongzhong.58.com/chuzu/',
    u'陵水': 'http://lingshui.58.com/chuzu/',
    u'东方': 'http://df.58.com/chuzu/',
    u'定安': 'http://da.58.com/chuzu/',
    u'澄迈': 'http://cm.58.com/chuzu/',
    u'保亭': 'http://baoting.58.com/chuzu/',
    u'白沙': 'http://baish.58.com/chuzu/',
    u'儋州': 'http://danzhou.58.com/chuzu/',

    u'郑州': 'http://zz.58.com/chuzu/',
    u'洛阳': 'http://luoyang.58.com/chuzu/',
    u'新乡': 'http://xx.58.com/chuzu/',
    u'南阳': 'http://ny.58.com/chuzu/',
    u'许昌': 'http://xc.58.com/chuzu/',
    u'平顶山': 'http://pds.58.com/chuzu/',
    u'安阳': 'http://ay.58.com/chuzu/',
    u'焦作': 'http://jiaozuo.58.com/chuzu/',
    u'商丘': 'http://sq.58.com/chuzu/',
    u'开封': 'http://kaifeng.58.com/chuzu/',
    u'濮阳': 'http://puyang.58.com/chuzu/',
    u'周口': 'http://zk.58.com/chuzu/',
    u'信阳': 'http://xy.58.com/chuzu/',
    u'驻马店': 'http://zmd.58.com/chuzu/',
    u'漯河': 'http://luohe.58.com/chuzu/',
    u'三门峡': 'http://smx.58.com/chuzu/',
    u'鹤壁': 'http://hb.58.com/chuzu/',
    u'济源': 'http://jiyuan.58.com/chuzu/',
    u'明港': 'http://mg.58.com/chuzu/',
    u'鄢陵': 'http://yanling.58.com/chuzu/',
    u'禹州': 'http://yuzhou.58.com/chuzu/',
    u'长葛': 'http://changge.58.com/chuzu/',
    u'灵宝': 'http://lingbaoshi.58.com/chuzu/',
    u'杞县': 'http://qixianqu.58.com/chuzu/',
    u'汝州': 'http://ruzhou.58.com/chuzu/',
    u'项城': 'http://xiangchengshi.58.com/chuzu/',
    u'偃师': 'http://yanshiqu.58.com/chuzu/',
    u'长垣': 'http://changyuan.58.com/chuzu/',
    u'滑县': 'http://huaxian.58.com/chuzu/',
    u'林州': 'http://linzhou.58.com/chuzu/',
    u'沁阳': 'http://qinyang.58.com/chuzu/',
    u'孟州': 'http://mengzhou.58.com/chuzu/',
    u'温县': 'http://wenxian.58.com/chuzu/',
    u'尉氏': 'http://weishixian.58.com/chuzu/',
    u'兰考': 'http://lankaoxian.58.com/chuzu/',
    u'通许': 'http://tongxuxian.58.com/chuzu/',
    u'新安': 'http://lyxinan.58.com/chuzu/',
    u'伊川': 'http://yichuan.58.com/chuzu/',
    u'孟津': 'http://mengjinqu.58.com/chuzu/',
    u'宜阳': 'http://lyyiyang.58.com/chuzu/',
    u'舞钢': 'http://wugang.58.com/chuzu/',
    u'永城': 'http://yongcheng.58.com/chuzu/',
    u'睢县': 'http://suixian.58.com/chuzu/',
    u'鹿邑': 'http://luyi.58.com/chuzu/',
    u'渑池': 'http://yingchixian.58.com/chuzu/',
    u'沈丘': 'http://shenqiu.58.com/chuzu/',
    u'太康': 'http://taikang.58.com/chuzu/',
    u'商水': 'http://shangshui.58.com/chuzu/',
    u'淇县': 'http://qixianq.58.com/chuzu/',
    u'浚县': 'http://junxian.58.com/chuzu/',
    u'范县': 'http://fanxian.58.com/chuzu/',
    u'固始': 'http://gushixian.58.com/chuzu/',
    u'淮滨': 'http://huaibinxian.58.com/chuzu/',
    u'邓州': 'http://dengzhou.58.com/chuzu/',
    u'新野': 'http://xinye.58.com/chuzu/',

    u'哈尔滨': 'http://hrb.58.com/chuzu/',
    u'大庆': 'http://dq.58.com/chuzu/',
    u'齐齐哈尔': 'http://qqhr.58.com/chuzu/',
    u'牡丹江': 'http://mdj.58.com/chuzu/',
    u'绥化': 'http://suihua.58.com/chuzu/',
    u'佳木斯': 'http://jms.58.com/chuzu/',
    u'鸡西': 'http://jixi.58.com/chuzu/',
    u'双鸭山': 'http://sys.58.com/chuzu/',
    u'鹤岗': 'http://hegang.58.com/chuzu/',
    u'黑河': 'http://heihe.58.com/chuzu/',
    u'伊春': 'http://yich.58.com/chuzu/',
    u'七台河': 'http://qth.58.com/chuzu/',
    u'大兴安岭': 'http://dxal.58.com/chuzu/',
    u'安达': 'http://shanda.58.com/chuzu/',
    u'肇东': 'http://shzhaodong.58.com/chuzu/',
    u'肇州': 'http://zhaozhou.58.com/chuzu/',

    u'武汉': 'http://wh.58.com/chuzu/',
    u'宜昌': 'http://yc.58.com/chuzu/',
    u'襄阳': 'http://xf.58.com/chuzu/',
    u'荆州': 'http://jingzhou.58.com/chuzu/',
    u'十堰': 'http://shiyan.58.com/chuzu/',
    u'黄石': 'http://hshi.58.com/chuzu/',
    u'孝感': 'http://xiaogan.58.com/chuzu/',
    u'黄冈': 'http://hg.58.com/chuzu/',
    u'恩施': 'http://es.58.com/chuzu/',
    u'荆门': 'http://jingmen.58.com/chuzu/',
    u'咸宁': 'http://xianning.58.com/chuzu/',
    u'鄂州': 'http://ez.58.com/chuzu/',
    u'随州': 'http://suizhou.58.com/chuzu/',
    u'潜江': 'http://qianjiang.58.com/chuzu/',
    u'天门': 'http://tm.58.com/chuzu/',
    u'仙桃': 'http://xiantao.58.com/chuzu/',
    u'神农架': 'http://snj.58.com/chuzu/',
    u'宜都': 'http://yidou.58.com/chuzu/',
    u'汉川': 'http://hanchuan.58.com/chuzu/',
    u'枣阳': 'http://zaoyang.58.com/chuzu/',
    u'武穴': 'http://wuxueshi.58.com/chuzu/',
    u'钟祥': 'http://zhongxiangshi.58.com/chuzu/',
    u'京山': 'http://jingshanxian.58.com/chuzu/',
    u'沙洋': 'http://shayangxian.58.com/chuzu/',
    u'松滋': 'http://songzi.58.com/chuzu/',
    u'广水': 'http://guangshuishi.58.com/chuzu/',
    u'赤壁': 'http://chibishi.58.com/chuzu/',
    u'老河口': 'http://laohekou.58.com/chuzu/',
    u'谷城': 'http://gucheng.58.com/chuzu/',
    u'宜城': 'http://yichengshi.58.com/chuzu/',
    u'南漳': 'http://nanzhang.58.com/chuzu/',
    u'云梦': 'http://yunmeng.58.com/chuzu/',
    u'安陆': 'http://anlu.58.com/chuzu/',
    u'大悟': 'http://dawu.58.com/chuzu/',
    u'孝昌': 'http://xiaochang.58.com/chuzu/',
    u'当阳': 'http://dangyang.58.com/chuzu/',
    u'枝江': 'http://zhijiang.58.com/chuzu/',
    u'嘉鱼': 'http://jiayuxian.58.com/chuzu/',
    u'随县': 'http://suixia.58.com/chuzu/',

    u'长沙': 'http://cs.58.com/chuzu/',
    u'株洲': 'http://zhuzhou.58.com/chuzu/',
    u'益阳': 'http://yiyang.58.com/chuzu/',
    u'常德': 'http://changde.58.com/chuzu/',
    u'衡阳': 'http://hy.58.com/chuzu/',
    u'湘潭': 'http://xiangtan.58.com/chuzu/',
    u'岳阳': 'http://yy.58.com/chuzu/',
    u'郴州': 'http://chenzhou.58.com/chuzu/',
    u'邵阳': 'http://shaoyang.58.com/chuzu/',
    u'怀化': 'http://hh.58.com/chuzu/',
    u'永州': 'http://yongzhou.58.com/chuzu/',
    u'娄底': 'http://ld.58.com/chuzu/',
    u'湘西': 'http://xiangxi.58.com/chuzu/',
    u'张家界': 'http://zjj.58.com/chuzu/',
    u'醴陵': 'http://liling.58.com/chuzu/',
    u'澧县': 'http://lixian.58.com/chuzu/',
    u'桂阳': 'http://czguiyang.58.com/chuzu/',
    u'资兴': 'http://zixing.58.com/chuzu/',
    u'永兴': 'http://yongxing.58.com/chuzu/',
    u'常宁': 'http://changningshi.58.com/chuzu/',
    u'祁东': 'http://qidongxian.58.com/chuzu/',
    u'衡东': 'http://hengdong.58.com/chuzu/',
    u'冷水江': 'http://lengshuijiangshi.58.com/chuzu/',
    u'涟源': 'http://lianyuanshi.58.com/chuzu/',
    u'双峰': 'http://shuangfengxian.58.com/chuzu/',
    u'邵阳县': 'http://shaoyangxian.58.com/chuzu/',
    u'邵东': 'http://shaodongxian.58.com/chuzu/',
    u'沅江': 'http://yuanjiangs.58.com/chuzu/',
    u'南县': 'http://nanxian.58.com/chuzu/',
    u'祁阳': 'http://qiyang.58.com/chuzu/',
    u'湘阴': 'http://xiangyin.58.com/chuzu/',
    u'华容': 'http://huarong.58.com/chuzu/',
    u'慈利': 'http://cilixian.58.com/chuzu/',
    u'攸县': 'http://zzyouxian.58.com/chuzu/',

    u'石家庄': 'http://sjz.58.com/chuzu/',
    u'保定': 'http://bd.58.com/chuzu/',
    u'唐山': 'http://ts.58.com/chuzu/',
    u'廊坊': 'http://lf.58.com/chuzu/',
    u'邯郸': 'http://hd.58.com/chuzu/',
    u'秦皇岛': 'http://qhd.58.com/chuzu/',
    u'沧州': 'http://cangzhou.58.com/chuzu/',
    u'邢台': 'http://xt.58.com/chuzu/',
    u'衡水': 'http://hs.58.com/chuzu/',
    u'张家口': 'http://zjk.58.com/chuzu/',
    u'承德': 'http://chengde.58.com/chuzu/',
    u'定州': 'http://dingzhou.58.com/chuzu/',
    u'馆陶': 'http://gt.58.com/chuzu/',
    u'张北': 'http://zhangbei.58.com/chuzu/',
    u'赵县': 'http://zx.58.com/chuzu/',
    u'正定': 'http://zd.58.com/chuzu/',
    u'迁安市': 'http://qianan.58.com/chuzu/',
    u'任丘': 'http://renqiu.58.com/chuzu/',
    u'三河': 'http://sanhe.58.com/chuzu/',
    u'武安': 'http://wuan.58.com/chuzu/',
    u'雄安新区': 'http://xionganxinqu.58.com/chuzu/',
    u'燕郊': 'http://lfyanjiao.58.com/chuzu/',
    u'涿州': 'http://zhuozhou.58.com/chuzu/',
    u'河间': 'http://hejian.58.com/chuzu/',
    u'黄骅': 'http://huanghua.58.com/chuzu/',
    u'沧县': 'http://cangxian.58.com/chuzu/',
    u'磁县': 'http://cixian.58.com/chuzu/',
    u'涉县': 'http://shexian.58.com/chuzu/',
    u'霸州': 'http://bazhou.58.com/chuzu/',
    u'香河': 'http://xianghe.58.com/chuzu/',
    u'固安': 'http://lfguan.58.com/chuzu/',
    u'遵化市': 'http://zunhua.58.com/chuzu/',
    u'迁西': 'http://qianxixian.58.com/chuzu/',
    u'玉田': 'http://yutianxian.58.com/chuzu/',
    u'滦南': 'http://luannanxian.58.com/chuzu/',
    u'沙河': 'http://shaheshi.58.com/chuzu/',
    # J

    u'苏州': 'http://su.58.com/chuzu/',
    u'南京': 'http://nj.58.com/chuzu/',
    u'无锡': 'http://wx.58.com/chuzu/',
    u'常州': 'http://cz.58.com/chuzu/',
    u'徐州': 'http://xz.58.com/chuzu/',
    u'南通': 'http://nt.58.com/chuzu/',
    u'扬州': 'http://yz.58.com/chuzu/',
    u'盐城': 'http://yancheng.58.com/chuzu/',
    u'淮安': 'http://ha.58.com/chuzu/',
    u'连云港': 'http://lyg.58.com/chuzu/',
    u'泰州': 'http://taizhou.58.com/chuzu/',
    u'宿迁': 'http://suqian.58.com/chuzu/',
    u'镇江': 'http://zj.58.com/chuzu/',
    u'沭阳': 'http://shuyang.58.com/chuzu/',
    u'大丰': 'http://dafeng.58.com/chuzu/',
    u'如皋': 'http://rugao.58.com/chuzu/',
    u'启东': 'http://qidong.58.com/chuzu/',
    u'溧阳': 'http://liyang.58.com/chuzu/',
    u'海门': 'http://haimen.58.com/chuzu/',
    u'东海': 'http://donghai.58.com/chuzu/',
    u'扬中': 'http://yangzhong.58.com/chuzu/',
    u'兴化': 'http://xinghuashi.58.com/chuzu/',
    u'新沂': 'http://xinyishi.58.com/chuzu/',
    u'泰兴': 'http://taixing.58.com/chuzu/',
    u'如东': 'http://rudong.58.com/chuzu/',
    u'邳州': 'http://pizhou.58.com/chuzu/',
    u'沛县': 'http://xzpeixian.58.com/chuzu/',
    u'靖江': 'http://jingjiang.58.com/chuzu/',
    u'建湖': 'http://jianhu.58.com/chuzu/',
    u'海安': 'http://haian.58.com/chuzu/',
    u'东台': 'http://dongtai.58.com/chuzu/',
    u'丹阳': 'http://danyang.58.com/chuzu/',
    u'宝应县': 'http://baoyingx.58.com/chuzu/',
    u'灌南': 'http://guannan.58.com/chuzu/',
    u'灌云': 'http://guanyun.58.com/chuzu/',
    u'姜堰': 'http://jiangyan.58.com/chuzu/',
    u'金坛': 'http://jintan.58.com/chuzu/',
    u'昆山': 'http://szkunshan.58.com/chuzu/',
    u'泗洪': 'http://sihong.58.com/chuzu/',
    u'泗阳': 'http://siyang.58.com/chuzu/',
    u'句容': 'http://jurong.58.com/chuzu/',
    u'射阳': 'http://sheyang.58.com/chuzu/',
    u'阜宁': 'http://funingxian.58.com/chuzu/',
    u'响水': 'http://xiangshui.58.com/chuzu/',
    u'盱眙': 'http://xuyi.58.com/chuzu/',
    u'金湖': 'http://jinhu.58.com/chuzu/',

    u'南昌': 'http://nc.58.com/chuzu/',
    u'赣州': 'http://ganzhou.58.com/chuzu/',
    u'九江': 'http://jj.58.com/chuzu/',
    u'宜春': 'http://yichun.58.com/chuzu/',
    u'吉安': 'http://ja.58.com/chuzu/',
    u'上饶': 'http://sr.58.com/chuzu/',
    u'萍乡': 'http://px.58.com/chuzu/',
    u'抚州': 'http://fuzhou.58.com/chuzu/',
    u'景德镇': 'http://jdz.58.com/chuzu/',
    u'新余': 'http://xinyu.58.com/chuzu/',
    u'鹰潭': 'http://yingtan.58.com/chuzu/',
    u'永新': 'http://yxx.58.com/chuzu/',
    u'乐平': 'http://lepingshi.58.com/chuzu/',
    u'进贤': 'http://jinxian.58.com/chuzu/',
    u'分宜': 'http://fenyi.58.com/chuzu/',
    u'丰城': 'http://fengchengshi.58.com/chuzu/',
    u'樟树': 'http://zhangshu.58.com/chuzu/',
    u'高安': 'http://gaoan.58.com/chuzu/',
    u'余江': 'http://yujiang.58.com/chuzu/',
    u'南城': 'http://nanchengx.58.com/chuzu/',
    u'浮梁': 'http://fuliangxian.58.com/chuzu/',

    u'长春': 'http://cc.58.com/chuzu/',
    u'吉林': 'http://jl.58.com/chuzu/',
    u'四平': 'http://sp.58.com/chuzu/',
    u'延边': 'http://yanbian.58.com/chuzu/',
    u'松原': 'http://songyuan.58.com/chuzu/',
    u'白城': 'http://bc.58.com/chuzu/',
    u'通化': 'http://th.58.com/chuzu/',
    u'白山': 'http://baishan.58.com/chuzu/',
    u'辽源': 'http://liaoyuan.58.com/chuzu/',
    u'公主岭': 'http://gongzhuling.58.com/chuzu/',
    u'梅河口': 'http://meihekou.58.com/chuzu/',
    u'扶余': 'http://fuyuxian.58.com/chuzu/',
    u'长岭': 'http://changlingxian.58.com/chuzu/',
    u'桦甸': 'http://huadian.58.com/chuzu/',
    u'磐石': 'http://panshi.58.com/chuzu/',
    u'梨树县': 'http://lishu.58.com/chuzu/',
    # L

    u'沈阳': 'http://sy.58.com/chuzu/',
    u'大连': 'http://dl.58.com/chuzu/',
    u'鞍山': 'http://as.58.com/chuzu/',
    u'锦州': 'http://jinzhou.58.com/chuzu/',
    u'抚顺': 'http://fushun.58.com/chuzu/',
    u'营口': 'http://yk.58.com/chuzu/',
    u'盘锦': 'http://pj.58.com/chuzu/',
    u'朝阳': 'http://cy.58.com/chuzu/',
    u'丹东': 'http://dandong.58.com/chuzu/',
    u'辽阳': 'http://liaoyang.58.com/chuzu/',
    u'本溪': 'http://benxi.58.com/chuzu/',
    u'葫芦岛': 'http://hld.58.com/chuzu/',
    u'铁岭': 'http://tl.58.com/chuzu/',
    u'阜新': 'http://fx.58.com/chuzu/',
    u'庄河': 'http://pld.58.com/chuzu/',
    u'瓦房店': 'http://wfd.58.com/chuzu/',
    u'灯塔': 'http://dengta.58.com/chuzu/',
    u'凤城': 'http://fengcheng.58.com/chuzu/',
    u'北票': 'http://beipiao.58.com/chuzu/',
    u'开原': 'http://kaiyuan.58.com/chuzu/',
    # N

    u'银川': 'http://yinchuan.58.com/chuzu/',
    u'吴忠': 'http://wuzhong.58.com/chuzu/',
    u'石嘴山': 'http://szs.58.com/chuzu/',
    u'中卫': 'http://zw.58.com/chuzu/',
    u'固原': 'http://guyuan.58.com/chuzu/',

    u'呼和浩特': 'http://hu.58.com/chuzu/',
    u'包头': 'http://bt.58.com/chuzu/',
    u'赤峰': 'http://chifeng.58.com/chuzu/',
    u'鄂尔多斯': 'http://erds.58.com/chuzu/',
    u'通辽': 'http://tongliao.58.com/chuzu/',
    u'呼伦贝尔': 'http://hlbe.58.com/chuzu/',
    u'巴彦淖尔市': 'http://bycem.58.com/chuzu/',
    u'乌兰察布': 'http://wlcb.58.com/chuzu/',
    u'锡林郭勒': 'http://xl.58.com/chuzu/',
    u'兴安盟': 'http://xam.58.com/chuzu/',
    u'乌海': 'http://wuhai.58.com/chuzu/',
    u'阿拉善盟': 'http://alsm.58.com/chuzu/',
    u'海拉尔': 'http://hlr.58.com/chuzu/',
    # Q

    u'西宁': 'http://xn.58.com/chuzu/',
    u'海西': 'http://hx.58.com/chuzu/',
    u'海北': 'http://haibei.58.com/chuzu/',
    u'果洛': 'http://guoluo.58.com/chuzu/',
    u'海东': 'http://haidong.58.com/chuzu/',
    u'黄南': 'http://huangnan.58.com/chuzu/',
    u'玉树': 'http://ys.58.com/chuzu/',
    u'海南': 'http://hainan.58.com/chuzu/',
    u'格尔木': 'http://geermushi.58.com/chuzu/',
    # S

    u'青岛': 'http://qd.58.com/chuzu/',
    u'济南': 'http://jn.58.com/chuzu/',
    u'烟台': 'http://yt.58.com/chuzu/',
    u'潍坊': 'http://wf.58.com/chuzu/',
    u'临沂': 'http://linyi.58.com/chuzu/',
    u'淄博': 'http://zb.58.com/chuzu/',
    u'济宁': 'http://jining.58.com/chuzu/',
    u'泰安': 'http://ta.58.com/chuzu/',
    u'聊城': 'http://lc.58.com/chuzu/',
    u'威海': 'http://weihai.58.com/chuzu/',
    u'枣庄': 'http://zaozhuang.58.com/chuzu/',
    u'德州': 'http://dz.58.com/chuzu/',
    u'日照': 'http://rizhao.58.com/chuzu/',
    u'东营': 'http://dy.58.com/chuzu/',
    u'菏泽': 'http://heze.58.com/chuzu/',
    u'滨州': 'http://bz.58.com/chuzu/',
    u'莱芜': 'http://lw.58.com/chuzu/',
    u'章丘': 'http://zhangqiu.58.com/chuzu/',
    u'垦利': 'http://kl.58.com/chuzu/',
    u'诸城': 'http://zc.58.com/chuzu/',
    u'寿光': 'http://shouguang.58.com/chuzu/',
    u'龙口': 'http://longkou.58.com/chuzu/',
    u'曹县': 'http://caoxian.58.com/chuzu/',
    u'单县': 'http://shanxian.58.com/chuzu/',
    u'肥城': 'http://feicheng.58.com/chuzu/',
    u'高密': 'http://gaomi.58.com/chuzu/',
    u'广饶': 'http://guangrao.58.com/chuzu/',
    u'桓台': 'http://huantaixian.58.com/chuzu/',
    u'莒县': 'http://juxian.58.com/chuzu/',
    u'莱州': 'http://laizhou.58.com/chuzu/',
    u'蓬莱': 'http://penglai.58.com/chuzu/',
    u'青州': 'http://qingzhou.58.com/chuzu/',
    u'荣成': 'http://rongcheng.58.com/chuzu/',
    u'乳山': 'http://rushan.58.com/chuzu/',
    u'滕州': 'http://tengzhou.58.com/chuzu/',
    u'新泰': 'http://xintai.58.com/chuzu/',
    u'招远': 'http://zhaoyuan.58.com/chuzu/',
    u'邹城': 'http://zoucheng.58.com/chuzu/',
    u'邹平': 'http://zouping.58.com/chuzu/',
    u'临清': 'http://linqing.58.com/chuzu/',
    u'茌平': 'http://chiping.58.com/chuzu/',
    u'郓城': 'http://hzyc.58.com/chuzu/',
    u'博兴': 'http://boxing.58.com/chuzu/',
    u'东明': 'http://dongming.58.com/chuzu/',
    u'巨野': 'http://juye.58.com/chuzu/',
    u'无棣': 'http://wudi.58.com/chuzu/',
    u'齐河': 'http://qihe.58.com/chuzu/',
    u'微山': 'http://weishan.58.com/chuzu/',
    u'禹城': 'http://yuchengshi.58.com/chuzu/',
    u'临邑': 'http://linyixianq.58.com/chuzu/',
    u'乐陵': 'http://leling.58.com/chuzu/',
    u'莱阳': 'http://laiyang.58.com/chuzu/',
    u'宁津': 'http://ningjin.58.com/chuzu/',
    u'高唐': 'http://gaotang.58.com/chuzu/',
    u'莘县': 'http://shenxian.58.com/chuzu/',
    u'阳谷': 'http://yanggu.58.com/chuzu/',
    u'冠县': 'http://guanxian.58.com/chuzu/',
    u'平邑': 'http://pingyi.58.com/chuzu/',
    u'郯城': 'http://tancheng.58.com/chuzu/',
    u'沂源': 'http://yiyuanxian.58.com/chuzu/',
    u'汶上': 'http://wenshang.58.com/chuzu/',
    u'梁山': 'http://liangshanx.58.com/chuzu/',
    u'利津': 'http://lijin.58.com/chuzu/',
    u'沂南': 'http://yinanxian.58.com/chuzu/',
    u'栖霞': 'http://qixia.58.com/chuzu/',
    u'宁阳': 'http://ningyang.58.com/chuzu/',
    u'东平': 'http://dongping.58.com/chuzu/',
    u'昌邑': 'http://changyishi.58.com/chuzu/',
    u'安丘': 'http://anqiu.58.com/chuzu/',
    u'昌乐': 'http://changle.58.com/chuzu/',
    u'临朐': 'http://linqu.58.com/chuzu/',
    u'鄄城': 'http://juancheng.58.com/chuzu/',

    u'太原': 'http://ty.58.com/chuzu/',
    u'临汾': 'http://linfen.58.com/chuzu/',
    u'大同': 'http://dt.58.com/chuzu/',
    u'运城': 'http://yuncheng.58.com/chuzu/',
    u'晋中': 'http://jz.58.com/chuzu/',
    u'长治': 'http://changzhi.58.com/chuzu/',
    u'晋城': 'http://jincheng.58.com/chuzu/',
    u'阳泉': 'http://yq.58.com/chuzu/',
    u'吕梁': 'http://lvliang.58.com/chuzu/',
    u'忻州': 'http://xinzhou.58.com/chuzu/',
    u'朔州': 'http://shuozhou.58.com/chuzu/',
    u'临猗': 'http://linyixian.58.com/chuzu/',
    u'清徐': 'http://qingxu.58.com/chuzu/',
    u'柳林': 'http://liulin.58.com/chuzu/',
    u'高平': 'http://gaoping.58.com/chuzu/',
    u'泽州': 'http://zezhou.58.com/chuzu/',
    u'襄垣': 'http://xiangyuanxian.58.com/chuzu/',
    u'孝义': 'http://xiaoyi.58.com/chuzu/',

    u'西安': 'http://xa.58.com/chuzu/',
    u'咸阳': 'http://xianyang.58.com/chuzu/',
    u'宝鸡': 'http://baoji.58.com/chuzu/',
    u'渭南': 'http://wn.58.com/chuzu/',
    u'汉中': 'http://hanzhong.58.com/chuzu/',
    u'榆林': 'http://yl.58.com/chuzu/',
    u'延安': 'http://yanan.58.com/chuzu/',
    u'安康': 'http://ankang.58.com/chuzu/',
    u'商洛': 'http://sl.58.com/chuzu/',
    u'铜川': 'http://tc.58.com/chuzu/',
    u'神木': 'http://shenmu.58.com/chuzu/',
    u'韩城': 'http://hancheng.58.com/chuzu/',
    u'府谷': 'http://fugu.58.com/chuzu/',
    u'靖边': 'http://jingbian.58.com/chuzu/',
    u'定边': 'http://dingbian.58.com/chuzu/',

    u'成都': 'http://cd.58.com/chuzu/',
    u'绵阳': 'http://mianyang.58.com/chuzu/',
    u'德阳': 'http://deyang.58.com/chuzu/',
    u'南充': 'http://nanchong.58.com/chuzu/',
    u'宜宾': 'http://yb.58.com/chuzu/',
    u'自贡': 'http://zg.58.com/chuzu/',
    u'乐山': 'http://ls.58.com/chuzu/',
    u'泸州': 'http://luzhou.58.com/chuzu/',
    u'达州': 'http://dazhou.58.com/chuzu/',
    u'内江': 'http://scnj.58.com/chuzu/',
    u'遂宁': 'http://suining.58.com/chuzu/',
    u'攀枝花': 'http://panzhihua.58.com/chuzu/',
    u'眉山': 'http://ms.58.com/chuzu/',
    u'广安': 'http://ga.58.com/chuzu/',
    u'资阳': 'http://zy.58.com/chuzu/',
    u'凉山': 'http://liangshan.58.com/chuzu/',
    u'广元': 'http://guangyuan.58.com/chuzu/',
    u'雅安': 'http://ya.58.com/chuzu/',
    u'巴中': 'http://bazhong.58.com/chuzu/',
    u'阿坝': 'http://ab.58.com/chuzu/',
    u'甘孜': 'http://ganzi.58.com/chuzu/',
    u'安岳': 'http://anyuexian.58.com/chuzu/',
    u'广汉': 'http://guanghanshi.58.com/chuzu/',
    u'简阳': 'http://jianyangshi.58.com/chuzu/',
    u'仁寿': 'http://renshouxian.58.com/chuzu/',
    u'射洪': 'http://shehongxian.58.com/chuzu/',
    u'大竹': 'http://dazu.58.com/chuzu/',
    u'宣汉': 'http://xuanhan.58.com/chuzu/',
    u'渠县': 'http://qux.58.com/chuzu/',
    u'长宁': 'http://changningx.58.com/chuzu/',
    # X

    u'乌鲁木齐': 'http://xj.58.com/chuzu/',
    u'昌吉': 'http://changji.58.com/chuzu/',
    u'巴音郭楞': 'http://bygl.58.com/chuzu/',
    u'伊犁': 'http://yili.58.com/chuzu/',
    u'阿克苏': 'http://aks.58.com/chuzu/',
    u'喀什': 'http://ks.58.com/chuzu/',
    u'哈密': 'http://hami.58.com/chuzu/',
    u'克拉玛依': 'http://klmy.58.com/chuzu/',
    u'博尔塔拉': 'http://betl.58.com/chuzu/',
    u'吐鲁番': 'http://tlf.58.com/chuzu/',
    u'和田': 'http://ht.58.com/chuzu/',
    u'石河子': 'http://shz.58.com/chuzu/',
    u'克孜勒苏': 'http://kzls.58.com/chuzu/',
    u'阿拉尔': 'http://ale.58.com/chuzu/',
    u'五家渠': 'http://wjq.58.com/chuzu/',
    u'图木舒克': 'http://tmsk.58.com/chuzu/',
    u'库尔勒': 'http://kel.58.com/chuzu/',
    u'阿勒泰': 'http://alt.58.com/chuzu/',
    u'塔城': 'http://tac.58.com/chuzu/',

    u'拉萨': 'http://lasa.58.com/chuzu/',
    u'日喀则': 'http://rkz.58.com/chuzu/',
    u'山南': 'http://sn.58.com/chuzu/',
    u'林芝': 'http://linzhi.58.com/chuzu/',
    u'昌都': 'http://changdu.58.com/chuzu/',
    u'那曲': 'http://nq.58.com/chuzu/',
    u'阿里': 'http://al.58.com/chuzu/',
    u'日土': 'http://rituxian.58.com/chuzu/',
    u'改则': 'http://gaizexian.58.com/chuzu/',
    # Y

    u'昆明': 'http://km.58.com/chuzu/',
    u'曲靖': 'http://qj.58.com/chuzu/',
    u'大理': 'http://dali.58.com/chuzu/',
    u'红河': 'http://honghe.58.com/chuzu/',
    u'玉溪': 'http://yx.58.com/chuzu/',
    u'丽江': 'http://lj.58.com/chuzu/',
    u'文山': 'http://ws.58.com/chuzu/',
    u'楚雄': 'http://cx.58.com/chuzu/',
    u'西双版纳': 'http://bn.58.com/chuzu/',
    u'昭通': 'http://zt.58.com/chuzu/',
    u'德宏': 'http://dh.58.com/chuzu/',
    u'普洱': 'http://pe.58.com/chuzu/',
    u'保山': 'http://bs.58.com/chuzu/',
    u'临沧': 'http://lincang.58.com/chuzu/',
    u'迪庆': 'http://diqing.58.com/chuzu/',
    u'怒江': 'http://nujiang.58.com/chuzu/',
    u'弥勒': 'http://milexian.58.com/chuzu/',
    u'安宁': 'http://anningshi.58.com/chuzu/',
    u'宣威': 'http://xuanwushi.58.com/chuzu/',
    # Z

    u'杭州': 'http://hz.58.com/chuzu/',
    u'宁波': 'http://nb.58.com/chuzu/',
    u'温州': 'http://wz.58.com/chuzu/',
    u'金华': 'http://jh.58.com/chuzu/',
    u'嘉兴': 'http://jx.58.com/chuzu/',
    u'台州': 'http://tz.58.com/chuzu/',
    u'绍兴': 'http://sx.58.com/chuzu/',
    u'湖州': 'http://huzhou.58.com/chuzu/',
    u'丽水': 'http://lishui.58.com/chuzu/',
    u'衢州': 'http://quzhou.58.com/chuzu/',
    u'舟山': 'http://zhoushan.58.com/chuzu/',
    u'乐清': 'http://yueqingcity.58.com/chuzu/',
    u'瑞安': 'http://ruiancity.58.com/chuzu/',
    u'义乌': 'http://yiwu.58.com/chuzu/',
    u'余姚': 'http://yuyao.58.com/chuzu/',
    u'诸暨': 'http://zhuji.58.com/chuzu/',
    u'象山': 'http://xiangshanxian.58.com/chuzu/',
    u'温岭': 'http://wenling.58.com/chuzu/',
    u'桐乡': 'http://tongxiang.58.com/chuzu/',
    u'慈溪': 'http://cixi.58.com/chuzu/',
    u'长兴': 'http://changxing.58.com/chuzu/',
    u'嘉善': 'http://jiashanx.58.com/chuzu/',
    u'海宁': 'http://haining.58.com/chuzu/',
    u'德清': 'http://deqing.58.com/chuzu/',
    u'东阳': 'http://dongyang.58.com/chuzu/',
    u'安吉': 'http://anji.58.com/chuzu/',
    u'苍南': 'http://cangnanxian.58.com/chuzu/',
    u'临海': 'http://linhai.58.com/chuzu/',
    u'永康': 'http://yongkang.58.com/chuzu/',
    u'玉环': 'http://yuhuan.58.com/chuzu/',
    u'平湖': 'http://pinghushi.58.com/chuzu/',
    u'海盐': 'http://haiyan.58.com/chuzu/',
    u'武义县': 'http://wuyix.58.com/chuzu/',
    u'嵊州': 'http://shengzhou.58.com/chuzu/',
    u'新昌': 'http://xinchang.58.com/chuzu/',
    u'江山': 'http://jiangshanshi.58.com/chuzu/',
    u'平阳': 'http://pingyangxian.58.com/chuzu/',

    # 其他
    u'香港': 'http://hk.58.com/chuzu/',
    u'澳门': 'http://am.58.com/chuzu/',
    u'台湾': 'http://tw.58.com/chuzu/',
    u'全国': 'http://quanguo.58.com/chuzu/',
    u'其他': 'http://cn.58.com/chuzu/',

    # 海外
    u'洛杉矶': 'http://g.58.com/j-gllosangeles/',
    u'旧金山': 'http://g.58.com/j-glsanfrancisco/',
    u'纽约': 'http://g.58.com/j-glnewyork/',
    u'多伦多': 'http://g.58.com/j-gltoronto/',
    u'温哥华': 'http://g.58.com/j-glvancouver/',
    u'伦敦': 'http://g.58.com/j-glgreaterlondon/',
    u'莫斯科': 'http://g.58.com/j-glmoscow/',
    u'首尔': 'http://g.58.com/j-glseoul/',
    u'东京': 'http://g.58.com/j-gltokyo/',
    u'新加坡': 'http://g.58.com/j-glsingapore/',
    u'曼谷': 'http://g.58.com/j-glbangkok/',
    u'清迈': 'http://g.58.com/j-glchiangmai/',
    u'迪拜': 'http://g.58.com/j-gldubai/',
    u'奥克兰': 'http://g.58.com/j-glauckland/',
    u'悉尼': 'http://g.58.com/j-glsydney/',
    u'墨尔本': 'http://g.58.com/j-glmelbourne/',
    u'其他海外城市': 'http://g.58.com/city/',
}
